# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9d43ce6a83d5fabe0a3115ac9a2e012c558668be15412bc567a8a3335b159c59908840a612bcd442ec64b0da7a5352da8e44eae702493baa9bac094463f4e96

test:
  secret_key_base: 14b0052f88339641de18e7058279820dd31009b48b7ea36904a663c95f151e5118fe9b88a0684ab8ae75e2f6e48b62ac9cb99af6f89987ef9f2f5738237afe7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
